services:
  backend:
    build: .
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    environment:
      JWT_SECRET: 76mxWxLbZlzVR8YNxFqHbYci/7io/QkLeUvkK0KuQrc=
      SPRING_APPLICATION_NAME: Personal Finance Tracker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/finance
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: